Data load Oversampled dataset with majority class  25% hidden


In [ ]:
import pickle
import numpy as np
import pandas as pd

df_train = pd.read_csv("w_red_train.csv")
df_test = pd.read_csv("w_red_test.csv")

with open('red_10_hidden_221130.pkl', 'rb') as f:
  data = pickle.load(f)

In [ ]:
columns = list(df_train.columns)

if 'quality' in columns:
  columns.remove('quality')
if 'type' in columns:
  columns.remove('type')

X_train = df_train[columns]
y_train = df_train['quality']

X_test = df_test[columns]
y_test = df_test['quality']

#### Classification and Result with SMOTE

Construct New training set by Combining new samples applied validation system

In [ ]:
smote_val=data[0][data[0]['quality'] == data[0]['closest_class']]
smote_v3 = smote_val[smote_val['quality'] == 3].sample(n =409, random_state = 0 )
smote_v4 = smote_val[smote_val['quality'] == 4].sample(n =381, random_state = 0 )
smote_v7 = smote_val[smote_val['quality'] == 7].sample(n =286, random_state = 0 )
smote_v8 = smote_val[smote_val['quality'] == 8].sample(n =403, random_state = 0 )
smote_1 = pd.concat([smote_v3, smote_v4], ignore_index = True)
smote_2 = pd.concat([smote_1,smote_v7], ignore_index = True)
smote_100 = pd.concat([smote_2, smote_v8], ignore_index = True)

In [ ]:
df_train_sm = pd.concat([df_train, smote_100], axis = 0, ignore_index = True)

In [ ]:
columns = list(df_train.columns)

if 'type' in columns:
  columns.remove('type')
if 'quality' in columns:
  columns.remove('quality')

X_train = df_train_sm[columns]
y_train = df_train_sm['quality']

In [ ]:
X_test = df_test[columns]
y_test = df_test['quality']

1. Random Forest

In [ ]:
# RF
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state = 0)
clf.fit(X_train, y_train)

rf_y_pred = clf.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, rf_y_pred))
print(classification_report(y_test, rf_y_pred))

[[  1   1   2   0   0   0]
 [  2   3   9   4   1   0]
 [  3  11 185  38   1   0]
 [  0   4  62 131  24   2]
 [  0   0   1  19  49   1]
 [  0   0   0   1   5   0]]
              precision    recall  f1-score   support

           3       0.17      0.25      0.20         4
           4       0.16      0.16      0.16        19
           5       0.71      0.78      0.74       238
           6       0.68      0.59      0.63       223
           7       0.61      0.70      0.65        70
           8       0.00      0.00      0.00         6

    accuracy                           0.66       560
   macro avg       0.39      0.41      0.40       560
weighted avg       0.66      0.66      0.66       560



2. GBM

In [ ]:
# GBM
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(random_state = 0)
clf = clf.fit(X_train, y_train)

gbm_y_pred = clf.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, gbm_y_pred))
print(classification_report(y_test, gbm_y_pred))

[[  1   2   0   1   0   0]
 [  1   2  12   3   1   0]
 [  2  12 166  54   4   0]
 [  0  13  53 115  41   1]
 [  0   0   0  24  43   3]
 [  0   0   0   0   6   0]]
              precision    recall  f1-score   support

           3       0.25      0.25      0.25         4
           4       0.07      0.11      0.08        19
           5       0.72      0.70      0.71       238
           6       0.58      0.52      0.55       223
           7       0.45      0.61      0.52        70
           8       0.00      0.00      0.00         6

    accuracy                           0.58       560
   macro avg       0.35      0.36      0.35       560
weighted avg       0.60      0.58      0.59       560



3. Logistic Regression

In [ ]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state = 0)
clf = clf.fit(X_train, y_train)

lr_y_pred = clf.predict(X_test)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, lr_y_pred))
print(classification_report(y_test, lr_y_pred))

[[  1   2   0   1   0   0]
 [  4   8   3   0   2   2]
 [ 24  55 109  38  10   2]
 [ 25  46  28  57  40  27]
 [  4   1   1  15  30  19]
 [  0   0   0   0   5   1]]
              precision    recall  f1-score   support

           3       0.02      0.25      0.03         4
           4       0.07      0.42      0.12        19
           5       0.77      0.46      0.58       238
           6       0.51      0.26      0.34       223
           7       0.34      0.43      0.38        70
           8       0.02      0.17      0.04         6

    accuracy                           0.37       560
   macro avg       0.29      0.33      0.25       560
weighted avg       0.58      0.37      0.43       560



4. KNN

In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

knn_y_pred = knn.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, knn_y_pred))
print(classification_report(y_test, knn_y_pred))

[[  1   1   0   1   1   0]
 [  2   4   5   5   2   1]
 [  5  31 135  46  18   3]
 [  5  29  64  77  37  11]
 [  1   7   8  14  35   5]
 [  0   0   0   0   6   0]]
              precision    recall  f1-score   support

           3       0.07      0.25      0.11         4
           4       0.06      0.21      0.09        19
           5       0.64      0.57      0.60       238
           6       0.54      0.35      0.42       223
           7       0.35      0.50      0.41        70
           8       0.00      0.00      0.00         6

    accuracy                           0.45       560
   macro avg       0.28      0.31      0.27       560
weighted avg       0.53      0.45      0.48       560



#### Classification and Result with ADASYN

Construct New training set by Combining new samples applied validation system

In [ ]:
ads_val=data[1][data[1]['quality'] == data[1]['closest_class']]
ads_v3 = ads_val[ads_val['quality'] == 3].sample(n =409, random_state = 0 )
ads_v4 = ads_val[ads_val['quality'] == 4].sample(n =381, random_state = 0 )
ads_v7 = ads_val[ads_val['quality'] == 7].sample(n =286, random_state = 0 )
ads_v8 = ads_val[ads_val['quality'] == 8].sample(n =403, random_state = 0 )
ads_1 = pd.concat([ads_v3, ads_v4], ignore_index = True)
ads_2 = pd.concat([ads_1,ads_v7], ignore_index = True)
ads_100 = pd.concat([ads_2, ads_v8], ignore_index = True)


In [ ]:
df_train_ads = pd.concat([df_train, ads_100], axis = 0, ignore_index = True)

In [ ]:
X_train = df_train_ads[columns]
y_train = df_train_ads['quality']

1. Random Forest

In [ ]:
# RF
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state = 0)
clf.fit(X_train, y_train)

rf_y_pred = clf.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, rf_y_pred))
print(classification_report(y_test, rf_y_pred))

[[  1   1   1   1   0   0]
 [  0   4   8   6   1   0]
 [  1  13 177  45   2   0]
 [  0   6  59 129  27   2]
 [  0   0   1  22  46   1]
 [  0   0   0   1   5   0]]
              precision    recall  f1-score   support

           3       0.50      0.25      0.33         4
           4       0.17      0.21      0.19        19
           5       0.72      0.74      0.73       238
           6       0.63      0.58      0.60       223
           7       0.57      0.66      0.61        70
           8       0.00      0.00      0.00         6

    accuracy                           0.64       560
   macro avg       0.43      0.41      0.41       560
weighted avg       0.64      0.64      0.64       560



2. GBM

In [ ]:
# GBM
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(random_state = 0)
clf = clf.fit(X_train, y_train)

gbm_y_pred = clf.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, gbm_y_pred))
print(classification_report(y_test, gbm_y_pred))

[[  1   2   0   1   0   0]
 [  1   4  10   3   1   0]
 [  0  14 170  51   3   0]
 [  0   8  55 125  33   2]
 [  0   0   2  24  38   6]
 [  0   0   0   1   5   0]]
              precision    recall  f1-score   support

           3       0.50      0.25      0.33         4
           4       0.14      0.21      0.17        19
           5       0.72      0.71      0.72       238
           6       0.61      0.56      0.58       223
           7       0.47      0.54      0.51        70
           8       0.00      0.00      0.00         6

    accuracy                           0.60       560
   macro avg       0.41      0.38      0.39       560
weighted avg       0.62      0.60      0.61       560



3. Logistic Regression

In [ ]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state = 0)
clf = clf.fit(X_train, y_train)

lr_y_pred = clf.predict(X_test)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, lr_y_pred))
print(classification_report(y_test, lr_y_pred))

[[  1   1   1   1   0   0]
 [  3   8   4   1   1   2]
 [ 20  43 129  34  10   2]
 [ 20  30  47  61  43  22]
 [  2   0   3  14  32  19]
 [  0   0   0   0   5   1]]
              precision    recall  f1-score   support

           3       0.02      0.25      0.04         4
           4       0.10      0.42      0.16        19
           5       0.70      0.54      0.61       238
           6       0.55      0.27      0.37       223
           7       0.35      0.46      0.40        70
           8       0.02      0.17      0.04         6

    accuracy                           0.41       560
   macro avg       0.29      0.35      0.27       560
weighted avg       0.56      0.41      0.46       560



4. KNN

In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

knn_y_pred = knn.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, knn_y_pred))
print(classification_report(y_test, knn_y_pred))

[[  1   1   0   0   2   0]
 [  3   5   4   3   2   2]
 [  5  44 126  37  20   6]
 [  5  31  63  66  38  20]
 [  1   6   7   9  40   7]
 [  0   0   0   0   6   0]]
              precision    recall  f1-score   support

           3       0.07      0.25      0.11         4
           4       0.06      0.26      0.09        19
           5       0.63      0.53      0.58       238
           6       0.57      0.30      0.39       223
           7       0.37      0.57      0.45        70
           8       0.00      0.00      0.00         6

    accuracy                           0.42       560
   macro avg       0.28      0.32      0.27       560
weighted avg       0.55      0.42      0.46       560



#### Classification and Result with SMOTE Tomek

Construct New training set by Combining new samples applied validation system

In [ ]:
smt_val=data[2][data[2]['quality'] == data[2]['closest_class']]
smt_v3 = smt_val[smt_val['quality'] == 3].sample(n =409, random_state = 0 )
smt_v4 = smt_val[smt_val['quality'] == 4].sample(n =381, random_state = 0 )
smt_v7 = smt_val[smt_val['quality'] == 7].sample(n =286, random_state = 0 )
smt_v8 = smt_val[smt_val['quality'] == 8].sample(n =403, random_state = 0 )
smt_1 = pd.concat([smt_v3, smt_v4], ignore_index = True)
smt_2 = pd.concat([smt_1,smt_v7], ignore_index = True)
smt_100 = pd.concat([smt_2, smt_v8], ignore_index = True)

In [ ]:
df_train_smt = pd.concat([df_train, smt_100], axis = 0, ignore_index = True)

In [ ]:
X_train = df_train_smt[columns]
y_train = df_train_smt['quality']

1. Random Forest

In [ ]:
# RF
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state = 0)
clf.fit(X_train, y_train)

rf_y_pred = clf.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, rf_y_pred))
print(classification_report(y_test, rf_y_pred))

[[  1   1   1   1   0   0]
 [  2   3   9   4   1   0]
 [  3  14 178  43   0   0]
 [  0   6  54 134  27   2]
 [  0   0   1  21  47   1]
 [  0   0   0   0   6   0]]
              precision    recall  f1-score   support

           3       0.17      0.25      0.20         4
           4       0.12      0.16      0.14        19
           5       0.73      0.75      0.74       238
           6       0.66      0.60      0.63       223
           7       0.58      0.67      0.62        70
           8       0.00      0.00      0.00         6

    accuracy                           0.65       560
   macro avg       0.38      0.40      0.39       560
weighted avg       0.65      0.65      0.65       560



2. GBM

In [ ]:
# GBM
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(random_state = 0)
clf = clf.fit(X_train, y_train)

gbm_y_pred = clf.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, gbm_y_pred))
print(classification_report(y_test, gbm_y_pred))

[[  1   2   0   1   0   0]
 [  1   2  12   4   0   0]
 [  1  12 169  51   5   0]
 [  0  10  57 119  35   2]
 [  0   0   0  30  37   3]
 [  0   0   0   0   6   0]]
              precision    recall  f1-score   support

           3       0.33      0.25      0.29         4
           4       0.08      0.11      0.09        19
           5       0.71      0.71      0.71       238
           6       0.58      0.53      0.56       223
           7       0.45      0.53      0.48        70
           8       0.00      0.00      0.00         6

    accuracy                           0.59       560
   macro avg       0.36      0.35      0.35       560
weighted avg       0.59      0.59      0.59       560



3. Logistic Regression

In [ ]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state = 0)
clf = clf.fit(X_train, y_train)

lr_y_pred = clf.predict(X_test)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, lr_y_pred))
print(classification_report(y_test, lr_y_pred))

[[  1   1   1   1   0   0]
 [  4   4   5   3   1   2]
 [ 23  35 113  58   7   2]
 [ 23  21  36  78  37  28]
 [  2   0   1  15  32  20]
 [  0   0   0   0   5   1]]
              precision    recall  f1-score   support

           3       0.02      0.25      0.04         4
           4       0.07      0.21      0.10        19
           5       0.72      0.47      0.57       238
           6       0.50      0.35      0.41       223
           7       0.39      0.46      0.42        70
           8       0.02      0.17      0.03         6

    accuracy                           0.41       560
   macro avg       0.29      0.32      0.26       560
weighted avg       0.56      0.41      0.46       560



4. KNN

In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

knn_y_pred = knn.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, knn_y_pred))
print(classification_report(y_test, knn_y_pred))

[[  1   1   0   1   1   0]
 [  2   4   6   4   2   1]
 [  5  29 138  44  19   3]
 [  5  28  64  75  40  11]
 [  1   7   6  14  37   5]
 [  0   0   0   0   6   0]]
              precision    recall  f1-score   support

           3       0.07      0.25      0.11         4
           4       0.06      0.21      0.09        19
           5       0.64      0.58      0.61       238
           6       0.54      0.34      0.42       223
           7       0.35      0.53      0.42        70
           8       0.00      0.00      0.00         6

    accuracy                           0.46       560
   macro avg       0.28      0.32      0.28       560
weighted avg       0.54      0.46      0.48       560



#### Classification and Result with Boderline SMOTE

Construct New training set by Combining new samples applied validation system

In [ ]:
bsm_val=data[3][data[3]['quality'] == data[3]['closest_class']]
bsm_v4 = bsm_val[bsm_val['quality'] == 4].sample(n =381, random_state = 0 )
bsm_v7 = bsm_val[bsm_val['quality'] == 7].sample(n =286, random_state = 0 )
bsm_100 = pd.concat([bsm_v4, bsm_v7], ignore_index = True)

In [ ]:
df_train_bsm = pd.concat([df_train, bsm_100], axis = 0, ignore_index = True)

In [ ]:
X_train = df_train_bsm[columns]
y_train = df_train_bsm['quality']

1. Random Forest

In [ ]:
# RF
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state = 0)
clf.fit(X_train, y_train)

rf_y_pred = clf.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, rf_y_pred))
print(classification_report(y_test, rf_y_pred))

[[  0   1   2   1   0   0]
 [  0   2   9   7   1   0]
 [  0   6 193  36   3   0]
 [  0   3  66 124  30   0]
 [  0   0   2  22  46   0]
 [  0   0   0   0   6   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.17      0.11      0.13        19
           5       0.71      0.81      0.76       238
           6       0.65      0.56      0.60       223
           7       0.53      0.66      0.59        70
           8       0.00      0.00      0.00         6

    accuracy                           0.65       560
   macro avg       0.34      0.35      0.35       560
weighted avg       0.63      0.65      0.64       560



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2. GBM

In [ ]:
# GBM
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(random_state = 0)
clf = clf.fit(X_train, y_train)

gbm_y_pred = clf.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, gbm_y_pred))
print(classification_report(y_test, gbm_y_pred))

[[  0   2   1   1   0   0]
 [  0   4  10   4   1   0]
 [  1  13 167  53   3   1]
 [  0  10  52 126  34   1]
 [  0   0   1  27  40   2]
 [  0   0   0   0   6   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.14      0.21      0.17        19
           5       0.72      0.70      0.71       238
           6       0.60      0.57      0.58       223
           7       0.48      0.57      0.52        70
           8       0.00      0.00      0.00         6

    accuracy                           0.60       560
   macro avg       0.32      0.34      0.33       560
weighted avg       0.61      0.60      0.60       560



3. Logistic Regression

In [ ]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state = 0)
clf = clf.fit(X_train, y_train)

lr_y_pred = clf.predict(X_test)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, lr_y_pred))
print(classification_report(y_test, lr_y_pred))

[[  0   2   1   1   0   0]
 [  0  11   4   2   2   0]
 [  0  47 147  28  16   0]
 [  0  30  66  62  63   2]
 [  0   1   4  17  48   0]
 [  0   0   0   0   6   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.12      0.58      0.20        19
           5       0.66      0.62      0.64       238
           6       0.56      0.28      0.37       223
           7       0.36      0.69      0.47        70
           8       0.00      0.00      0.00         6

    accuracy                           0.48       560
   macro avg       0.28      0.36      0.28       560
weighted avg       0.55      0.48      0.49       560



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


4. KNN

In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

knn_y_pred = knn.predict(X_test)

Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, knn_y_pred))
print(classification_report(y_test, knn_y_pred))

[[  0   1   1   0   2   0]
 [  0   4   8   5   2   0]
 [  0  35 136  46  21   0]
 [  1  31  77  76  38   0]
 [  0   5  10  15  40   0]
 [  0   0   0   2   4   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.05      0.21      0.08        19
           5       0.59      0.57      0.58       238
           6       0.53      0.34      0.41       223
           7       0.37      0.57      0.45        70
           8       0.00      0.00      0.00         6

    accuracy                           0.46       560
   macro avg       0.26      0.28      0.25       560
weighted avg       0.51      0.46      0.47       560



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
