In [ ]:
import numpy as np
import pandas as pd

#### Original Dataset

In [ ]:
df_train = pd.read_csv("w_red_train.csv")
df_test = pd.read_csv("w_red_test.csv")

In [ ]:
columns = list(df_train.columns)

if 'quality' in columns:
  columns.remove('quality')
if 'type' in columns:
  columns.remove('type')

X_train = df_train[columns]
y_train = df_train['quality']

X_test = df_test[columns]
y_test = df_test['quality']

#### Classification and Results
- we use 4 types classifier <br>
Random Forest, GBM, logistic Regression and KNN <br>
Evaluation of model F1 score and confusion matrix


1. Random Forest

In [ ]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state = 0)
clf.fit(X_train, y_train)

rf_y_pred = clf.predict(X_test)

>  Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, rf_y_pred))
print(classification_report(y_test, rf_y_pred))

[[  0   0   4   0   0   0]
 [  0   1  13   4   1   0]
 [  0   0 195  43   0   0]
 [  0   0  65 147  11   0]
 [  0   0   3  35  31   1]
 [  0   0   0   5   1   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       1.00      0.05      0.10        19
           5       0.70      0.82      0.75       238
           6       0.63      0.66      0.64       223
           7       0.70      0.44      0.54        70
           8       0.00      0.00      0.00         6

    accuracy                           0.67       560
   macro avg       0.50      0.33      0.34       560
weighted avg       0.67      0.67      0.65       560



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2. GBM

In [ ]:
# GBM
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(random_state = 0)
clf = clf.fit(X_train, y_train)

gbm_y_pred = clf.predict(X_test)

>  Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, gbm_y_pred))
print(classification_report(y_test, gbm_y_pred))

[[  1   0   3   0   0   0]
 [  0   0  15   4   0   0]
 [  1   0 189  48   0   0]
 [  0   3  62 143  15   0]
 [  0   0   2  40  26   2]
 [  0   0   0   3   3   0]]
              precision    recall  f1-score   support

           3       0.50      0.25      0.33         4
           4       0.00      0.00      0.00        19
           5       0.70      0.79      0.74       238
           6       0.60      0.64      0.62       223
           7       0.59      0.37      0.46        70
           8       0.00      0.00      0.00         6

    accuracy                           0.64       560
   macro avg       0.40      0.34      0.36       560
weighted avg       0.61      0.64      0.62       560



3. Logistic Regression

In [ ]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state = 0)
clf = clf.fit(X_train, y_train)

lr_y_pred = clf.predict(X_test)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


>  Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, lr_y_pred))
print(classification_report(y_test, lr_y_pred))

[[  0   0   3   1   0   0]
 [  0   0  12   6   1   0]
 [  0   0 187  51   0   0]
 [  0   0  80 140   3   0]
 [  0   0   4  63   3   0]
 [  0   0   0   5   1   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00        19
           5       0.65      0.79      0.71       238
           6       0.53      0.63      0.57       223
           7       0.38      0.04      0.08        70
           8       0.00      0.00      0.00         6

    accuracy                           0.59       560
   macro avg       0.26      0.24      0.23       560
weighted avg       0.53      0.59      0.54       560



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


4. KNN

In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

knn_y_pred = knn.predict(X_test)

>  Evaluate


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, knn_y_pred))
print(classification_report(y_test, knn_y_pred))

[[  0   0   3   0   1   0]
 [  0   3  10   6   0   0]
 [  0  17 156  59   6   0]
 [  1  13  96  96  17   0]
 [  0   2  18  30  20   0]
 [  0   0   2   2   2   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.09      0.16      0.11        19
           5       0.55      0.66      0.60       238
           6       0.50      0.43      0.46       223
           7       0.43      0.29      0.34        70
           8       0.00      0.00      0.00         6

    accuracy                           0.49       560
   macro avg       0.26      0.25      0.25       560
weighted avg       0.49      0.49      0.48       560



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
